# Generated by Django 4.2.13 on 2024-06-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
